export default {
    PLEASE_ENTER: 'Please enter',
    PLEASE_ENTER_VALID: 'Please enter valid',
    PLEASE_ENTER_VALID_NUMERIC: 'Please enter numeric',
    NAME: 'name',
    EMAIL: 'email',
    Password_must_be: 'Password must be at least',
    FirstName_must_be: 'First name must be at least',
    characters: 'characters',
    PLEASE_ENTER_YOUR_FirstName: 'Please enter your first name',
    PLEASE_ENTER_YOUR_LastName: 'Please enter your last name',
    PLEASE_ENTER_YOUR_EMAIL: 'Please enter your email',
    PLEASE_ENTER_YOUR_PHONE_NUMBER: 'Please enter your phone number',
    PLEASE_ENTER_VALID_Name: 'Please enter valid name',
    PLEASE_ENTER_VALID_EMAIL: 'Please enter valid email',
    PLEASE_ENTER_VALID_PHONE_NUMBER: 'Please enter valid phone number',
    PLEASE_ENTER_PASSWORD: 'Please enter your password',
    PLEASE_ENTER_OLD_PASSWORD: 'Please enter your old password',
    PLEASE_ENTER_NEW_PASSWORD: 'Please enter your new password',
    PLEASE_ACCEPT_TERMS_FIRST: 'Please accept terms and conditions first to continue signup.',
    Password_must_have_a: 'Password must have a',
    Password_not_matched: 'Passwords not matched',
    PLEASE_ENTER_Confirm_PASSWORD: 'Please enter your confirm password',

    number: 'number',
    special_character: "special character",
    capital_letter: "capital letter",
    small_letter: "small letter",


    OTP: 'OTP',
    YOUR: 'YOUR',
    PASSWORD: 'password',
    CONFIRM_PASSWORD: 'confirm password',
    PASSWORD_NOT_MATCH: 'Password not matched',

    LOCATION_UNAVAILABLE: "Location not available",
    LOCATION_LIMITED: "Location limited access",
    LOCATION_UNAVAILABLE: "Loaction unavailable",
    LOCATION_DISABLED_MSG: "Are you want to disable location",

    ALLERT: "Alert !!",
    OPPS: "oops !!",
    Are_you_want_To_CLEAR_ALL_FILTERS: 'Are you want to clear all selected filters',
    Are_you_want_to_buy: 'Are you want to buy this deal',
    NO_DATA_FOUND: "Sorry you no data found.",
    EMPTY_TRASACTION_: "Sorry you don't have any transaction",
    EMPTY_Notification_: "Sorry you don't have any Notifiaction",

    EMPTY_DEAL: "Sorry no active deal available right now",
    EMPTY_CHATLIST: "Sorry you don't have any convesation",
    DELETE_OFFER: "Are you want to delete this offer",
    PLZ_CONNECT_WALLET: "Please connect wallet to continue",
    PLZ_ENTR_COIN_QTY: 'Please enter coins',
    PLZ_ENTR_VALID_COIN_QTY: 'Please enter valid coins',
    PLZ_ENTR_VALID_USER_ADDRESS: 'Please enter valid user address',


    INSUFFI_BALANCE_IN_YOUR_ACCOUNT: 'Insufficient balance in your account',

    PLZ_ENTR_WALLET_ADDRS: 'Please enter wallet address',
    WANT_TO_LOGOUT: 'Are you sure you want to log out your account.',
    WANT_TO_DELETE_ACCOUNT: `Are you sure you want to delete your account permanently? Once your account has been deleted, you will not be able to recover any pending coins. Please withdraw your coins before deleting your account. If you have already withdrawn your coins, please press 'Confirm' to delete your account.`,
    WARNING_BEFORE_START_TRADE:`Caution: Crypto trading involves significant risks. Be informed, stay vigilant, and only invest what you can afford to lose. Do thorough research, use secure platforms, and consider seeking professional advice. Remember, the crypto market is highly volatile and can lead to substantial losses. Trade responsibly.`,
ARE_YOU_WANT_TO_CREATE_OFFER: 'Create new offer ?',
    PLEASE_SELECT_ISSUE_TYPE: 'Please select issue type',
        PLEASE_ENTER_DISCRIPTION: 'Please enter discription',
}