export default{
Log_in:'Log in',
ResendOtp:'Resend OTP',
Signup: 'Signup',
Send: 'Send',
continue:'Continue',
Next:'Next',
forget_password:'Forgot password',
Buy:'Buy',
Completed:'Completed',
Pending:'Pending',
createOfffer:'CREATE OFFER',
changePassword:'Change Password',
editProfile:'Edit Profile',
tradeHistory:'Trade History',
offerHistory:'Offer History',

support:'Support',
currency_preference:'Currency Prefrence',
Notifications:'Notifications',
How_it_Works:'How it works',
F_A_Q:'FAQ',

logout:'Logout',
delete:'Delete',
deleteAccount:'Delete Account',

version:'Version',
Place_Sell_Order:'Place Sell Order',
Update_Place_Sell_Order:'Update & Place Sell Order',
Cancel:"Cancel",
Accept:'Accept',
Reinitiate:"Reinitiate",
Apply:'Apply',
Delete:'Delete',
Decline:'Decline',
ok : 'OK',
Connect:"Connect",
No:'No',
Yes:'Yes',
Confirm:"Confirm",
Back:"Back",
Deposit:'Deposit',
Withdraw:'Withdraw',
Transfer:'Transfer',
Modify_Offer:'Modify Offer',
Delete_Offer:'Delete Offer',
Choose_File:'Choose File',
Remove_file:'Remove file'
}